// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZfZfVslMIUk4d354fGOonRwA4ZaG_uQ',
    appId: '1:6721388689:web:78c6fe371df1a02944bf30',
    messagingSenderId: '6721388689',
    projectId: 'kapda-bazaar-394ce',
    authDomain: 'kapda-bazaar-394ce.firebaseapp.com',
    storageBucket: 'kapda-bazaar-394ce.appspot.com',
    measurementId: 'G-BY3RG8JY6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiXzqbl33oFc-K2cU0FFDvYrOr8i01o48',
    appId: '1:6721388689:android:59dd2fed3737e02544bf30',
    messagingSenderId: '6721388689',
    projectId: 'kapda-bazaar-394ce',
    storageBucket: 'kapda-bazaar-394ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3BASj-mxscZz3rKtAKfb80WlxgHtkmo',
    appId: '1:6721388689:ios:1f0df4bc1d0a2e9144bf30',
    messagingSenderId: '6721388689',
    projectId: 'kapda-bazaar-394ce',
    storageBucket: 'kapda-bazaar-394ce.appspot.com',
    iosBundleId: 'com.example.kapdaBazzar',
  );
}
